### ISSUE TITLE
Tracks no longer show in html files

### ISSUE THREAD

**Issue by lauhinojosa** [igvteam/igv-reports#101]
Hello,

Thanks for developing igv-reports.

Tracks do not load on HTML files that were previously working perfectly fine. In fact, none of the HTMLs that I had previously generated can load data. 

Is this an issue with the server or has there been a recent change (last couple of days) that affects the behavior? Is someone else experiencing this?
 
Thank you very much,
Laura Hinojosa

**Comment by jrobinso** [comment]
The data for tracks in an igv-reports html file are internal to the file.  Is it possible to share one of the reports?  If you send an email to igv-team@broadinstitute.org I can send you a secure dropbox link.

Of particular interest is what version of igv.js the reports are referencing.   This will be near the top of the html file.

**Comment by lauhinojosa** [comment]
Hi Jim,
Thank you for your quick reply.
The version is 2.9.1.

E-mail sent!

**Comment by jrobinso** [comment]
OK, got it.  Yes that is a problem caused by a change in our hosted genome file that is not compatible with 2.9.1.   I will fix it on our end, your reports should start working again shortly.

**Comment by lauhinojosa** [comment]
Perfect! Thank you very much!

**Comment by jrobinso** [comment]
OK they should be working again.

**Comment by jrobinso** [comment]
BTW that's an innovative use of igv-reports,  I take it you created a template file for this.  We don't really have much insight into how people are using this tool,  or if there is even much of a community, so this is nice to see.

**Comment by lauhinojosa** [comment]
Thank you very much for solving this so quickly! Everything is back to normal!
