### ISSUE TITLE
Could not load local index file 'ncbiRefSeq.txt.gz.tbi'

### ISSUE THREAD

**Issue by JunhuiLi1017** [igvteam/igv-reports#103]
Hi there, 

I was running create_report while a warning came out as below,

_Could not load local index file 'https://hgdownload.soe.ucsc.edu/goldenPath/hg19/database/ncbiRefSeq.txt.gz.tbi' : No such file or directory_

I have tried to find a parameter for this index in create_report, but there is no argument for this file. 

Please let me know if I missed something.

Thanks,
Junhui

**Comment by jrobinso** [comment]
The warning is normal, you can ignore it.
