### ISSUE TITLE
Alignment File Report Possible from "downsamples BAM"

### ISSUE THREAD

**Issue by jenzejoe2** [igvteam/igv-reports#104]
Hej IGV Team

First also from my side thanks for working on such a great project!

I'm referring to the Issue #75 with my issue.
I would like to produce html files from alined .bam files to a custom reference fasta as the above referred Issue asks.
As issue #75 I would not like to produce vcf files as all the information lies in the bam files already (indels).
The bam files are already downsampled to a desktop IGV compatible size (<10 MB) and could be downsample even more for this the here explained issue.
I also have at hand the location on in the ref fasta that I would like to have in the report.

Is it always needed to produce the vcf file even if there is only indels?

Could it be omitted with a "faked" vcf so that the only thing present  in the html report is the ref window as well as the coverage and reads from for this purpose downsampled bam files and the coverage?

(I know it sounds like a problem for the desktop IGV and a batch script still I would like to avoid the IGV desktop version or the command line version).

**Comment by jrobinso** [comment]
As noted in the documentation a VCF is not required, you can use "bed" files to define your regions.

**Comment by jenzejoe2** [comment]
> As noted in the documentation a VCF is not required, you can use "bed" files to define your regions.

This worked perfectly fine! Thanks for the hint!
