### ISSUE TITLE
Change default track height for tracks supplied via --tracks

### ISSUE THREAD

**Issue by phillip-richmond-umoja** [igvteam/igv-reports#109]
Hello!

This is an excellent package that you have created. I have a question about supplying configuration for the tracks via --track-config.

Right now, I'm running igv-reports as such:
```
    create_report \
	--fasta $genome_fasta \
	--output "GenesOfInterest_${enzyme_name}-sites_igvreport.html" \
	--tracks $genome_gtf $candidate_bed_pass $candidate_bed_fail $encode_cre $annotation_bedgraph \
	--flanking 10 \
	$target_regions
```

If I want all the tracks to have increased height, from 50 -> 100, is there a directive I can give to the --track-config json to specify this? Or would I need to define all the tracks I intend to show via --track-config, and not pass them via --tracks?

Thanks,
Phil

**Comment by jrobinso** [comment]
Hi, sorry for the long delay, I was pondering this then it fell off my list.  There is no global directive for track height, you would need to use --track-config.
