### ISSUE TITLE
Very slow to open with large BAM file sizes

### ISSUE THREAD

**Issue by yolanda-y-li** [igvteam/igv-reports#113]
Hello,

Thanks for creating this tool, it's great! I have a question about file sizes - is there a recommended size limit to the BAM files that are inputted to the program? 

For context, we often work with BAM files that are several hundred MB. We've tried already trimming down the BAM file using regions of interest, which cuts the size down by around 50%, as well as converting it to a CRAM file. The HTML page takes several minutes to open when we use a trimmed BAM file with about 100 MB. 

Thank you!

**Comment by jrobinso** [comment]
There is no limit on the size of the input BAM file.   How many sites (regions) are you defining, and with what file type (vcf or bed)?
