### ISSUE TITLE
Only display subset of tracks for specific variant rows

### ISSUE THREAD

**Issue by ErikEnsminger** [igvteam/igv-reports#114]
I have a maf file of 200 plus variants (i.e. rows) for +30 samples. Each row has a Tumor_Sample_Barcode and Matched_Norm_Sample_Barcode field denoting which sample this variant is found in. 
When setting the --tracks parameter, I just input all the bam file paths from my computer that exist in the maf file.
When running igv-reports, the output .html is super large as the variant is displayed for each track.
Is is possible to only display the variant for the select Tumor_Sample_Barcode, Matched_Norm_Sample_Barcode? 
For example, by selecting which rows/ variants of the maf get displayed for which tracks? 

Thank you.

**Comment by jrobinso** [comment]
I'm not sure I understand what you are proposing.  Controlling the display would not help reduce the size of the html as all data would still be extracted and saved in the file.    Extracting data from 200 BAM files is not realistic for this tool.

**Comment by ErikEnsminger** [comment]
Thank you for the quick reply. Yes, I realize my maf is a bit too big to do it at once. I have split my maf file into smaller files, and now running igv-report on each maf separately. Still works great.
