### ISSUE TITLE
<DEL> in alt field leads to crossed out entry in table

### ISSUE THREAD

**Issue by johanneskoester** [igvteam/igv-reports#15]
When a VCF file contains a `<DEL>` allele, the corresponding entry in the HTML table is not rendered correctly. Seems like the `<DEL>` is interpreted as HTML tag. I suggest to escape all VCF entries before rendering them in the table.

![igv-report-del-bug](https://user-images.githubusercontent.com/1858646/53291513-9aaa3e00-37b4-11e9-9cad-1b1f0752fb31.png)

**Comment by jrobinso** [comment]
Thanks for the report.  This is still in beta test phase,  I'm interested to learn more about how its being used if you care to share.

**Comment by johanneskoester** [comment]
Sure. I am evaluating the use in a personalized medicine pipeline, where tumor somatic variants are called on patient data.

**Comment by jrobinso** [comment]
Good to know, that's just the sort of application I had in mind.   I'll attend to this later today.
