### ISSUE TITLE
Display ID column in table

### ISSUE THREAD

**Issue by johanneskoester** [igvteam/igv-reports#17]
Usually, the ID column is used to present association with known variants. The table should be able to show this information. Ideally, it the user should be able to specify a URL pattern that shall be applied to the ID column in order to allow for a linkout. If nothing is provided the linkout could simply google the ID, or apply some heuristics to guess what should be the pattern. E.g., something starting with COSM should link out to COSMIC.

**Comment by jrobinso** [comment]
Thanks @johanneskoester Good suggestions,  I will set aside some time next week to work through these.
