### ISSUE TITLE
Present ANN field in a visual way

### ISSUE THREAD

**Issue by johanneskoester** [igvteam/igv-reports#18]
The table should automatically present the ANN field in a more accessible way. As far as I know it is now standardized across multiple annotation tools. I guess what makes sense is the following:

* Split by comma.
* Sort resulting items by impact.
* Have a nested table with the fields that are separated by pipes as columns.
* To save space, maybe only the first row should be shown and the others should be expandable. Frameworks like twitter bootstrap would make the latter quite easy.

**Comment by jrobinso** [comment]
I specifically do not use any frameworks in the template to keep it as light as possible.  However, the intent is to support other templates (user supplied) where this could be done.

**Comment by jrobinso** [comment]
This is beyond the scope for core development if reports (core == development I personally do).   I would welcome a pull request for this in the form of another template,  an advanced version of the basic variant_template.html used now.
