### ISSUE TITLE
Not all reads displayed

### ISSUE THREAD

**Issue by johanneskoester** [igvteam/igv-reports#21]
When I view my rendered HTMLs in the browser, it seems that at highly covered loci not all reads are displayed in the IGV panel. Is a downsampling step involved?

**Comment by jrobinso** [comment]
Downsampling occurs in igv.js itself.   See the https://github.com/igvteam/igv.js/wiki/Alignment-Track.  This is configurable but there is currently no way to set track configuration parameters in igv-reports.   For this particular class we could add a command-line flag  "no downsampling",  this would set the track config parameter "samplingDepth" to a very large number.   As a test try hardcoding this and see if you see more alignments.   If not there is another issue.

Note if downsampling occurs there will be a black bar under the coverage track in the region downsampled.

**Comment by jrobinso** [comment]
Hi @johanneskoester could you try the latest release?  Some enhancements were made to igv.js version 2.3.2 for very deep coverage files,  this did not involve downsampling but silent failure if the browser ran out of memory.  Normally this resulted in a browser crash, but for at least 1 user the failure was silent and not all reads displayed.  

Comments about downsampling above stilly apply, if this continues to be an problem reopen the issue.
