### ISSUE TITLE
High coverage BAMs needs to be downsampled in order to show reads

### ISSUE THREAD

**Issue by binfyun** [igvteam/igv-reports#24]
Hi,

I was able to display reads on two(T and N) bam tracks but only via downsampling the BAMs.  The downsample method I did removes the reads randomly and thus removes the alt reads (the variants). My questions are:

1. Is there a way to modify this limitation? (There was a similar post about not all reads displayed but I am sure if this is a related issue)
2. If 1. is not possible,  can you suggest a way to retain the alt reads (variants) when downsampling BAMs.
3. Can it be used to view structure variants and how would I go about including the SVs in the input vcf.

output HTML attached.
[igvjs_viewer.html.txt](https://github.com/igvteam/igv-reports/files/3086111/igvjs_viewer.html.txt)

Thanks

**Comment by jrobinso** [comment]
Hi, what version were you using?   I removed a limitation on the size of the session blob with a recent commit,  if you use the latest release (0.9.0) you will find it handles many more reads.  Of course there will always be a limitation,  your computer does not have infinite memory,  but it is larger now.

You will have to script something yourself to do downsampling that returns the alt reads.   That really isn't downsampling.   I don't know of any tool that does that.

SVs might be difficult if they cover a large genomic range, this is designed for snps and small indels at the current time.    Please open another issue requesting support for SVs,  also include details about what sort of SVs and what you expect to see.

**Comment by binfyun** [comment]
Hm..OK . Will give it a try,  Thank you.
