### ISSUE TITLE
Sorting option

### ISSUE THREAD

**Issue by binfyun** [igvteam/igv-reports#25]
Hi,

Is there a way to add more sorting options to the popup window when clicking on the reads.

Thanks

**Comment by jrobinso** [comment]
Hi Binfyun,

What would you like to sort by?

This is really an igv.js question,  but I assume you are using igv.js in the context of igv-reports?

**Comment by binfyun** [comment]
Hi @jrobinso 
Firing up IGV Apps and loading BAMs remotely are oftentimes troublesome.
Our goal is to be able to quickly and instantly visualize and ascertain certain variants during a meeting with the pathologist. 

Sort by insert size and chromosome of mate would be useful 👍

**Comment by jrobinso** [comment]
@binfyun Yes, that is exactly the use case igv-reports is designed for.  Please keep me informed on progress here, it's important for us to know.

I can add those sort options (again, this is really done in igv.js).   However you do understand that sorting is for a specific locus (base),  alignments that intersect that locus will be sorted by the chosen attribute.  Alignments that don't intersect the base are in random order.

**Comment by binfyun** [comment]
Hi @jrobinso,

Thank you for your responses and I was able to bring up more reads (used the whole bams without downsampling) per track.

There is a minor bug (or not a bug) on the COSMIC link. The COSMIC link always takes you to the expired ID (4006021 I believe?) and does not reflect the actual IDs in the VCF. Was it hardcoded? I was able to manually correct this by replacing each variant's COSMIC IDs in the "igvjs_viewer.html"

Thanks.

**Comment by jrobinso** [comment]
The link to cosmic is "hardcoded" but the IDs come from the VCF,  they are
not hardcoded.     If you can post a small VCF where the cosmic links are
incorrect I will look into it.

**Comment by petermchale** [comment]
@jrobinso : has your team implemented "Sort by insert size and chromosome of mate" in igv.js?

**Comment by jrobinso** [comment]
@petermchale they have, but not released yet,  it will be released early next week and I will update this project at that time.  Apologies to all for the long delay.

**Comment by jrobinso** [comment]
@petermchale New sorting options including insert size & chr of mate have been released.  The latest igv.js release is https://cdn.jsdelivr.net/npm/igv@2.3.3/dist/igv.min.js.  This is now the default for igv-reports.
