### ISSUE TITLE
Mistake in latest release number

### ISSUE THREAD

**Issue by FelixMoelder** [igvteam/igv-reports#31]
The latest release has been labeled with the release number 0.92 instead of 0.9.2.
As this would undermine the bioconda version history of igv-reports this should be corrected before updating the bioconda package.

**Comment by jrobinso** [comment]
@FelixMoelder Yes, my mistake, I'm not sure what the best way to correct this is.   The git tag is permanent,  I could republish 0.9.2 to pypi and delete 0.92,  what would you advise?

 Also,  I don't maintain a bioconda package for this.

**Comment by FelixMoelder** [comment]
I guess it would be easiest to delete and republish the release as you suggested.
I would update the bioconda package as soon as it is possible.

@johanneskoester Do you have any suggestions how to proceed?

**Comment by jrobinso** [comment]
@FelixMoelder I'm a bit confused as we don't publish a bioconda package.   At least to my knowledge.  I have many projects going so perhaps I've forgotten about something, but what are you referring to?

**Comment by FelixMoelder** [comment]
@jrobinso There is already an existing bioconda [package](https://anaconda.org/bioconda/igv-reports) of igv-reports 0.9.1.
As bioconda is open to everybody for contribution it is not necessary for you to maintain igv-reports there.

**Comment by jrobinso** [comment]
@FelixMoelder OK,  I don't know how it got there (to bioconda), I did not contribute it although I'm happy for it to be there.   I've corrected and pushed the tag to the git repository.

**Comment by FelixMoelder** [comment]
Perfect, thank you!
I will push an update of that version to bioconda.

**Comment by johanneskoester** [comment]
@jrobinso somebody from the community created the bioconda recipe. This is how bioconda is meant to work. We appreciate contributions by upstream devs, but otherwise software is packaged as needed, as long as the license allows it.
