### ISSUE TITLE
fix for integer Info columns not in latest release on pip

### ISSUE THREAD

**Issue by stevekm** [igvteam/igv-reports#47]
I followed the instructions in the README and installed with 

```
pip install igv-reports
```

However this gave me version 1.0.1. It seems like a number of important fixes are not included, importantly the ones in bbdf1e8

For example, the version of `igv-reports` I got off of [pip](https://pypi.org/project/igv-reports/) has the following for `varianttable.py`;

```
def render_value(v):
    """Render given value to string."""
    if isinstance(v, float):
        # ensure that we don't waste space by insignificant digits
        return f'{v:.2g}'
    elif v.startswith('http://') or v.startswith('https://'):
        return create_link(v)
    else:
        return str(v)
```

but the one I cloned off GitHub here has this, which fixes some bugs I was hitting;

```
def render_value(v):
    """Render given value to string."""
    if v is None:
        return ""
    elif isinstance(v, float):
        # ensure that we don't waste space by insignificant digits
        return f'{v:.2g}'
    elif isinstance(v, str):
        str_val = v.replace('"', '')
        
        if str_val.startswith('http://') or str_val.startswith('https://'):
            return create_link(str_val)
    
    return str(v)
```

Can there be a new release pushed to pip that includes these fixes? Thanks.

**Comment by jrobinso** [comment]
Apologies for the delay.   I don't know what happened there, but I just re-tagged as v1.0.2 and pushed a new release to pypi.
