### ISSUE TITLE
support for .tsv or .maf format input files

### ISSUE THREAD

**Issue by stevekm** [igvteam/igv-reports#50]
as mentioned here https://github.com/igvteam/igv-reports/issues/43, it would be really nice if `igv-reports` supported reading input from a tab separated or .maf input file. Right now it does not seem to work with that, forcing you to go through the process of converting your maf back into vcf to use it with `igv-reports`, which is a headache at times.

**Comment by jrobinso** [comment]
Bed files are tab delimited, and simple to create.

**Comment by stevekm** [comment]
bed is not a variant format though, generally when we are using IGV we want to load variants + bam together.

**Comment by jrobinso** [comment]
@stevekm Noted.   I'm going to set aside a couple of days to work on igv-reports next week.    I will add support for ".maf" at that time.  Could you possibly supply a small test file?   When I've worked with MAF in the past it seemed no two pipelines output the same thing,  there's a number of if-then tests in IGV desktop trying to figure out the MAF variant.  So it would be best if I had a sample of what you are actually using.

Also, as noted on another issue I updated the build at pypi and it should have the latest code now.   I don't know what happened with 1.0.1.

**Comment by jrobinso** [comment]
@stevekm Reminder to provide a small test file if you want your MAF variant supported.  Have a look at the 2 files just added to "test/data/maf".   These are from the IGV desktop project, both are referred to as "maf" files by different projects but they don't look much alike.   The file with the ".maf" extension looks like an actualy MAF file according to the old TCGA spec, the other is just an ad hoc format.   

So I can add support for a strictly spec (TCGA) compliant MAF file, or an ad hoc tab-delimited file,  but the latter will cover the former.   It will just mean an extra configuration parameter to define the required column numbers.    I think this is the path I will take as TCGA is no longer an active project and has no one looking after the spec, such as it is.

**Comment by jrobinso** [comment]
I've added support for TCGA MAF and generic tab delimited files,  see the updated readme.   This is not complete.  The variant table will be created from these files, but you can't display them as a track yet because igv.js itself does not support these formats.   I am going to pivot to igv.js to add support for this formats.   In the meantime you can test report generation with your MAF or other tab delimited files.

**Comment by jrobinso** [comment]
@stevekm OK I think this is done (not released to pipy yet).   See the example and readme.   TCGA "MAF" files should be supported now as is, with a ".maf" extension.   Alternatively, and for ad-hoc tab delimited formats, you can specify the required sequence, start, and end columns using tabix style parameters, as documented in the readme.  By default all column headers will be used in the table, but you can specify them with --info_columns, again see readme.  

As MAF and tsv files are not currently supported by igv.js a generic bed style track is automatically created to mark the variants.
