### ISSUE TITLE
Add IGV  'side-by-side' feature please.

### ISSUE THREAD

**Issue by xiucz** [igvteam/igv-reports#52]
Hi,
Thank you for your tools. In my recent fusion gene research,  how about add a new feature, which can be visualized side-by-side.
![image](https://user-images.githubusercontent.com/12706146/122323920-790f8a80-cf5a-11eb-815b-e80d0516a7f1.png)

Best, 
xiucz

**Comment by jrobinso** [comment]
This already exists, as your screenshot demonstrates, so I'm not sure what you are asking for.

**Comment by xiucz** [comment]
@jrobinso 
Thanks for your quick reply.  Yes, we can visualize fusion events in a GUI window manually. But how can I do it using `create_report` command line in batches? 

Best,
xiucz

**Comment by jrobinso** [comment]
Ahh, of course, gotcha.  You can't do that currently, its a good suggestion,  I will leave this open as a request.

**Comment by jrobinso** [comment]
@xiucz This is implemented thanks to help from @DevangThakkar .   See the README for instructions, you use a "bedpe" file to define the regions instead of a vcf.   This will be released in the next week.

**Comment by jrobinso** [comment]
Released as version 1.5.0
