### ISSUE TITLE
Down-sampling

### ISSUE THREAD

**Issue by azbard** [igvteam/igv-reports#61]
Is downsampling supported? The files I'm producing are way too large.

**Comment by jrobinso** [comment]
No, there is no downsampling option prior to creating the report.   This is complex, if we downsample before producing the report igv.js will not see all the reads and the coverage will be misleading.   If that is acceptable we could probably add a downsampling option with pysam.   I don't know when I could get to that, to be honest,  in the meantime I suggest you downsample your bam file with samtools before running igv-reports.
