### ISSUE TITLE
Request overhang softclip sequence view in igv reports

### ISSUE THREAD

**Issue by julie-asimov** [igvteam/igv-reports#66]
In the desktop IGV viewer when softclip reads are selected it will show the overhands at the ends of the reference. This is extremely useful for whole plasmid sequencing. Is this something that can be mirrored for IGV reports?

**Comment by jrobinso** [comment]
This is now supported with version 1.5.0

**Comment by andyjslee** [comment]
I used version `1.10.0` but don't see the softclip overhang. I ran the following code:
```
create_report test.bed \
  --genome hg38 \
  --flanking 10000 \
  --tracks test.bed test.bam \
  --output report.html
```
 I see the softclip overhang on IGV but not in the HTML report generated by igv-reports. Is there a special option to enable display of softclip overhang?

**Comment by jrobinso** [comment]
You can right-click on the gear menu, but if you want to configure it to show by default you will have to use the track configuration option `--track-config` rather than or in addition to `--tracks`.

**Comment by andyjslee** [comment]
Thank you!

**Comment by jrobinso** [comment]
You're welcome.  See the example.  

```
create_report test/data/variants/variants.vcf.gz \
--fasta https://igv-genepattern-org.s3.amazonaws.com/genomes/seq/hg38/hg38.fa \
--ideogram test/data/hg38/cytoBandIdeo.txt \
--flanking 1000 \
--info-columns GENE TISSUE TUMOR COSMIC_ID GENE SOMATIC \
--track-config test/data/variants/trackConfigs.json \
--output example_config.html
```
