### ISSUE TITLE
Copy Number Report

### ISSUE THREAD

**Issue by osmanwa** [igvteam/igv-reports#74]
Hi,

Could you tell me how to recreate this report:

https://igv.org/web/release/2.13.9/examples/copyNumber.html

from the igv.js repository with this cli tool?

I believe it only takes as input 1 file:

URL: https://s3.amazonaws.com/igv.org.demo/GBM-TP.seg.gz

Thanks

**Comment by jrobinso** [comment]
I'm confused by your question,  that is not an "igv-report" its an example of embedding "igv.js", a separate project.   See https://github.com/igvteam/igv.js.    

igv-reports do not support "seq" copy number files.

**Comment by osmanwa** [comment]
Any chance it will anytime soon?

**Comment by jrobinso** [comment]
Not without some compelling use case.
