### ISSUE TITLE
Why is variant sites a mandatory input for igv-reports

### ISSUE THREAD

**Issue by gopalpeddinti** [igvteam/igv-reports#75]
Hi, why is the variants file such as VCF a mandatory argument for igv-reports. Quite often I use IGV (the standalone app) to visualize the RNA-seq data (alignment files) along with just the reference genome and annotations (GFF) file. Is it possible to replicate such behavior using igv-reports so that the reports can be shared more easily withy my colleagues?

**Comment by jrobinso** [comment]
Because the point of igv-reports is to extract small portions of the file so it can be inserted into the html.    This would be impossible to do with an entire bam file.   Think about what you are trying to do.

**Comment by gopalpeddinti** [comment]
Thank you for you reply. Just a clarification, please: the `igv-tools` however also adds alignment tracks using BAM files, right?

**Comment by jrobinso** [comment]
What are you referring to by ```igv-tools```?

igv-reports supports CRAM and BAM files as inputs
