### ISSUE TITLE
Alignment track whitespace

### ISSUE THREAD

**Issue by ryanyord** [igvteam/igv-reports#81]
Hello,

When creating a track and using the following:

[{"name": "174545_SA31", "type": "alignment", "format": "bam", "url": "/bams/174545_SA31.markdup.sorted.bam", "indexURL": "/bams/174545_SA31.markdup.sorted.bam.bai", "showAlignments": false}

showAlignments = false , yet in the output a whitespace appears were the alignment track visual would be like in the following image:

<img width="1773" alt="image" src="https://github.com/igvteam/igv-reports/assets/85899130/71d8f875-2340-47e1-858a-d5895f507d6f">

However, It would be ideal to have it load like this:
<img width="1764" alt="image" src="https://github.com/igvteam/igv-reports/assets/85899130/9826c832-82df-49e8-b6b6-07fd316a905a">

I can get to the 2nd image by ticking and unticking the alignment track, but would love for it to display without whitespace as default.

Thank you, and appreciate the tool!

**Comment by jrobinso** [comment]
This should be fixed in the latest release
