### ISSUE TITLE
malposition of rows with tab and maf format input

### ISSUE THREAD

**Issue by jcd-gh** [igvteam/igv-reports#88]
The example **example_tab.html and example_maf.html** showed malposition of rows.
An extra line (i.e. the tittle row) was added to the top of the file, and the corresponding view was **shifted by one element**.

e.g.:
**chr	start	end	ref_allele	alt_allele**
chr	start	end	ref_allele	alt_allele  -> view of line 1, should be nothing
chr1	68897222	68897222	G	T   -> view of line 2, should be line 1
chr1	176760487	176760487	C	T   -> view of line 3, should be line 2

The problem is shown in version 1.8.0 and the current master branch, version 1.7.0 is not affected.

**Comment by jethror1** [comment]
I think this is the same issue as with generic tab delimited files as both are parsed by [GenericTable.from_tabfile()](https://github.com/igvteam/igv-reports/blob/0ac3ade3996dc427162d2c48463811f8816756e2/igv_reports/generictable.py#L10) which is called here

https://github.com/igvteam/igv-reports/blob/0ac3ade3996dc427162d2c48463811f8816756e2/igv_reports/report.py#L45-L47

This is addressed in this PR: https://github.com/igvteam/igv-reports/pull/89

**Comment by jrobinso** [comment]
@jethror1 is correct.   The PR is merged,  I will do a 1.8.1 release with this fix later today.

**Comment by jrobinso** [comment]
1.8.1 is released to pypi
