### ISSUE TITLE
create_report: error: unrecognized arguments: --zero-based false

### ISSUE THREAD

**Issue by yunkaig** [igvteam/igv-reports#92]
This is probably a minor issue, but the argument for "zero based" is called "**--zero-based**" (with a dash in between like other arguments) in the Github README doc. But the create_report script asks for "**--zero_based**" with an underscore in between words, according to the output of create_report -h. 

Not really a big issue but just so you are aware of this. Thanks!

**Comment by jrobinso** [comment]
Thanks for the report.  Stepping back a bit I'm not sure what motivated that argument.  The file formats excepted define this in there specs.  I suppose the only use-case for this if you use a generic (custom) tab-delimited file for your input.

I will update the README
