### ISSUE TITLE
fasta unrecognized

### ISSUE THREAD

**Issue by mzwaig** [igvteam/igv-reports#93]
Hi,

I'm trying to run create_report but I keep getting the following error when I give it genome fasta. 

`create_report: error: unrecognized arguments: --fasta /cvmfs/CentOS6/genomes/species/Homo_sapiens.GRCh38/genome/Homo_sapiens.GRCh38.fa`

There is a index file in the same folder so I'm not sure why it's not being accepted.

Thanks,
Melissa

**Comment by jrobinso** [comment]
Are you running the latest version?  Also, could you post your entire command line here?
