### ISSUE TITLE
Non human reference genome

### ISSUE THREAD

**Issue by erinyoung** [igvteam/igv-reports#95]
I don't think this is an error, but I would like to use this for a non-human genome. 

My use-case that I tried to get working was for SARS-COV-2, but I'd like to be able to use this for other genomes as well (especially bacterial).

Do you have examples of non-human genomes? Or user-supplied genomes? I don't have an ideogram.

**Comment by jrobinso** [comment]
You don't need a human genome, in fact igv.js has no idea what species is loaded,  you just need a fasta file.  Use the --fasta option not the --genome option as described in the README.  As noted in the README the ideogram is optinal.

**Comment by erinyoung** [comment]
Thanks!
